import 'package:floor/floor.dart';

/// This entity includes personal identification and license details.
/// The `id` is auto-generated by the database when inserting a new record.
@entity
class Customer {

  /// Primary key for the customer record.
  @primaryKey
  final int? id;

  /// The customer's first name.
  final String firstName;

  /// The customer's last name.
  final String lastName;

  /// The customer's home address.
  final String address;

  /// The customer's date of birth in string format.
  final String birthdate;

  /// The customer's driver's license number.
  final String licenseNo;

  /// Creates a new `Customer` with the provided information.
  /// The `id` is optional and typically assigned by the database when inserting.
  Customer({
    this.id,
    required this.firstName,
    required this.lastName,
    required this.address,
    required this.birthdate,
    required this.licenseNo,
  });
}