import 'package:floor/floor.dart';

/// This entity represents a boat for sale.
/// The `id` is auto-generated by the database when inserting a new record.
@entity
class Boat {

  /// Primary key for the boat record.
  @primaryKey
  final int? id;

  /// The year the boat was built.
  final String yearBuilt;

  /// The length of the boat.
  final String boatLength;

  /// The power type: sail or motor.
  final String powerType;

  /// The price of the boat.
  final String price;

  /// The address where the boat is located.
  final String address;

  /// Creates a new `Boat` with the provided information.
  /// The `id` is optional and typically assigned by the database when inserting.
  Boat({
    this.id,
    required this.yearBuilt,
    required this.boatLength,
    required this.powerType,
    required this.price,
    required this.address,
  });
}

